name = "ruralhaven"
compatibility_date = "2024-04-01"
main = "src/index.js"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[kv_namespaces]]
binding = "TRADING_KV"
id = "7897be3dd02240bcb61bcccc33ad6ec1"

[vars]
API_KEY = "1ea53bef7ef3111c599fbbc0b853a25253ff057178cca0bc16015805b82ee34b"
